### ISSUE TITLE
Docker image for raspberry pi

### ISSUE THREAD

**Issue by mattfusf** [Domochip/sms2mqtt#5]
Any chance you can provide a docker image for armv6 to run on Raspberry pi? Thanks

**Comment by petez69** [comment]
Hi there.....As per the above user, would love to use this on a Raspi....could we please get a version....

Thankyou..Pete

**Comment by Domochip** [comment]
Hi, just released it, could you give it a try?

**Comment by mattfusf** [comment]
Hey, thanks for remembering! Just tried it, and it seems to work. I'm having trouble receiving messages but sending works fine. (I suspect this is an issue with my modem/service, will have to troubleshoot)

**Comment by mattfusf** [comment]
I looked at another machine where I had gammu installed and needed to add
atgen_setcnmi = 1,2,0,0 to the gammurc file there to get it working; is there a way to inject that as an environment variable or otherwise when running this via docker-compose?

**Comment by Domochip** [comment]
The current generated file is gammurc one containing: 
```
[gammu]
device = {device}
connection = at
```

could you confirm what is the content of yours?

**Comment by mattfusf** [comment]
Thanks. On my self-installed gammu, the file is as follows:
`[gammu]
device = /dev/ttyUSB0
atgen_setcnmi = 1,2,0,0
connection = at`

I created a local Dockerfile and modified the sms2mqtt.py to do the same, but I'm afraid it still isn't working to receive messages.

**Comment by mattfusf** [comment]
Follow up: just for kicks, I tried adding this to the dockerfile
`RUN echo -ne "AT+CNMI=1,2,0,0\r" > /dev/mobile`

To my surprise - that seemed to do the trick. I'm sure there is a more elegant way to do this but it definitely appears to be an issue with the modem init.

**Comment by Domochip** [comment]
Could you try with latest-dev docker image and add GAMMUOPTION env variable.
like this : 
`docker run -d --name sms2mqtt -e GAMMUOPTION='atgen_setcnmi = 1,2,0,0' domochip/sms2mqtt:latest-dev`

**Comment by mattfusf** [comment]
Thanks. I did check to see that it added the line to gammurc correctly, but still couldn't receive messages. If I manually echo the command to the modem it works, so perhaps this is more of a gammu bug than anything else.
